name: reusable workflow

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: get test.sh
        uses: actions/checkout@v2
        with:
          repository: garrypas/test-workflows@main/scripts/deployment/test.sh
          ref: main
          path: scripts/deployment/test.sh

      - name: run test.sh
        run: |
          chmod +x scripts/deployment/test.sh
          bash scripts/deployment/test.sh

      - shell: bash
        run: |
          echo 'hello world'
