name: reusable workflow

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: get test.sh
        uses: actions/checkout@v2
        with:
          repository: garrypas/test-workflows
          ref: main
          path: .test-workflows@main

      - name: run test.sh
        run: |
          chmod +x .test-workflows/scripts/deployment/test.sh
          bash .test-workflows/scripts/deployment/test.sh
          rm -rf .test-workflows

      - shell: bash
        run: |
          echo 'hello world'
