name: reusable workflow

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: get test.sh
        uses: actions/checkout@v2
        with:
          repository: garrypas/workflow2
          ref: main
          path: .workflow2

      - name: run test.sh
        run: |
          ls
          chmod +x .workflow2/scripts/deployment/test.sh
          bash .workflow2/scripts/deployment/test.sh
          rm -rf .workflow2

      - shell: bash
        run: |
          echo 'hello world'
